analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_put_control_body_on_new_line
    - avoid_positional_boolean_parameters
    - cascade_invocations
    - document_ignores
    - prefer_expression_function_bodies
    - prefer_single_quotes
    - specify_nonobvious_local_variable_types
    - use_setters_to_change_properties
